---
apiVersion: v1
appVersion: "0.43.7-neurath.1"
description: "Container Storage Interface (CSI) driver for S3 volumes"
name: csi-s3
version: 0.43.7-neurath.1
keywords:
  - s3
home: https://github.com/neurath-ai/k8s-csi-s3
sources:
  - https://github.com/neurath-ai/k8s-csi-s3
